
import './globals.scss'


<meta name="viewport" content="width=device-width, initial-scale=1" />


export const metadata = {
  title: 'Portfolio Ryan ',
  description: 'Generated by Tamer Fouad'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body >
          {children}
      </body>

    </html>
  )
}
